### ISSUE TITLE
Unity, Unreal Asset store 사전 조사

### ISSUE THREAD

**Issue by jehyeon** [kookmin-sw/capstone-2023-19#17]

**Comment by jehyeon** [comment]
- 비슷한 에셋이 이미 있는지
- 우리가 사용할 텍스처와 반사 매핑 에셋 찾아보기

**Comment by loonl** [comment]
Unity
1. https://assetstore.unity.com/packages/tools/modeling/plants-growing-system-107128#description
Plants Growing System ($99.99) 
- 3D 식물 모델을 제공하면 그에 맞게 리얼 타임으로 성장하는 기능을 제공
- 특정 Parameter를 입력하면 그에 맞게 성장하는 기능을 제공
- 성장 과정의 Loop 가능, X, Y, Z축으로 회전도 가능

Unreal
2. https://www.unrealengine.com/marketplace/en-US/product/crazy-ivy-procedural-ivy-vine-generator-plug-in-auto-grow-plants-in-editor
Crazy Ivy Vine ($99.99)
- 덩쿨 성장 과정에 특화
- 다양한 Parameter를 지정하면 그에 맞게 성장하는 기능을 제공 - 1번보다 훨씬 다양한 것으로 파악 (예: 잎의 모양 지정 가능)
- 물체를 타고 올라가면서 성장

3. https://www.unrealengine.com/marketplace/en-US/product/procedural-growing-plants
Procedural Growing Plants ($19.99)
- 일반 잡초 종류만 지원
- Parameter로서 생성 개수, 생성 범위를  지정 가능
- 각 Grass 마다 충돌 감지가 가능한 것으로 추정

정해야 할 것 같은 방향성 : 에셋의 구체적인 목적 (예 : 게임 속에 사용이 가능한 에셋으로 만들 것인지, 테스트 케이스 생성을 위한 에셋을 노릴 것인지 등)
