### ISSUE TITLE
Preset Load Issue

### ISSUE THREAD

**Issue by jiwan1042** [kookmin-sw/capstone-2023-19#39]
Save한 Preset을 로드하면

-     Rule이 없어지는 이슈

-     Setting 파라미터 변하는 이슈

**Comment by jehyeon** [comment]
+ notion 검증 데이터 프리셋 등록하기

**Comment by jehyeon** [comment]
https://github.com/kookmin-sw/capstone-2023-19/pull/42
수정 완료

파라미터 변하는 이슈 재현 안됨
