### ISSUE TITLE
Context-Sensitive L-system 구현 및 검증

### ISSUE THREAD

**Issue by jehyeon** [kookmin-sw/capstone-2023-19#45]

**Comment by jehyeon** [comment]
### LRule
lSystem→AddRule() 할 때 같은 before이 있으면 after_에 추가
랜덤한 after를 꺼내도록 구현 ( vector\<vector\<LLetter\>\> )
#### 기존
context free after vector 하나만 존재
#### 추가
context sensitive after vector에서 선 검사, 없으면 free vector에서 확인
### LSystem::Iterate()
#### 기존
일치한 before가 있으면 바로 after로 대체 후 (v.insert) break
#### 개선
rule의 수가 점점 복잡해지기 때문에 O(n) search가 아닌 map으로 변경
word vector를 insert하며 사용하지 않고 iterate마다 output vector 생성
symbol 검사는 beforeWord에서, 대체된 after symbol은 afterWord vector에 push

**Comment by jehyeon** [comment]
c6171d2fc1b89834f199cd468f83191a7eeea048
5b18bcf8c613cd4c64bad0717b9e0635a662fa1a
49ea40e4e082e2ab8ad9f1e03467cacef5930e1b
92cc33ec7aa5e7bc70cbd53de8316c924b1b26ae

검증 케이스에서 검증 결과가 약간 다른 경우가 있음

코드 리뷰 및 원인 분석 이관 @loonl

**Comment by loonl** [comment]
https://github.com/kookmin-sw/capstone-2023-19/commit/e29fa9a5406182fcade442b37e0199837f27899d
https://github.com/kookmin-sw/capstone-2023-19/commit/32b86fdc64d7ad659f32273a2e386f72cc36b222
검증 케이스 모두 일치 - 수정완료

**Comment by loonl** [comment]
Parametric L-System 에서
