### ISSUE TITLE
다중 condition 지원 parametic l system context free

### ISSUE THREAD

**Issue by jehyeon** [kookmin-sw/capstone-2023-19#50]
동일한 format의 rule 랜덤 적용된 상태
다른 condition 동일 format rule의 경우, 랜덤 condition으로 rule 검증이 됨

f(5)
f(t) : t > 10 -> f(t+1)
f(t) : t <= 10 -> f(t - 1)
일 경우

t <= 10 rule이 적용되어야 함

현재는 랜덤으로 1개 선택해서 처리

parametic_test_3.txt

**Comment by loonl** [comment]
https://github.com/kookmin-sw/capstone-2023-19/commit/863c0ec07ed630ce2a8b50cbebc933322b36e9c2
https://github.com/kookmin-sw/capstone-2023-19/commit/9993dd9b19f78a3c5aaa4208a10edd5d281e3259
