### ISSUE TITLE
define 기능 추가하기 (Save, Load, UI) 

### ISSUE THREAD

**Issue by jehyeon** [kookmin-sw/capstone-2023-19#52]
#define CH 900

word: F(CH)
rule: 
F(t) : t > 800 -> F(CH, t + 100)
F(t, s) : t > 500 & s > 800 -> F(t + 100, s + 100)

word 혹은 rule after에서도 사용됨 
구현하기 어려우면 define symbol을 하나로 줄여도 좋을듯 (ex. CH -> C)

**Comment by loonl** [comment]
https://github.com/kookmin-sw/capstone-2023-19/commit/fad96ed680d8db11af09a3639146719d52deebfb

Condition, After에서 사용 가능 

TODO: UI에서 상수 추가 및 삭제 기능 구현

**Comment by 2sua** [comment]
상수와 value 값 추가 , 수정 및 삭제 UI 추가, 기능연결
디버깅용 L-system code  숨김 및 출력버튼 추가
