### ISSUE TITLE
Leaf 모델 추가하기

### ISSUE THREAD

**Issue by jehyeon** [kookmin-sw/capstone-2023-19#62]
2, 3가지 다른 모양
L(1) ~ L(5) 까지

**Comment by loonl** [comment]
https://github.com/kookmin-sw/capstone-2023-19/commit/4e50a33737fe84cda0c031371ab9bd52bfd2f5b6
https://github.com/kookmin-sw/capstone-2023-19/commit/9774173d0984282b648f393b76336549d4ecd8bc
https://github.com/kookmin-sw/capstone-2023-19/commit/ebc60823c318eeb2dec3ac9c99d53c71960060f6
