### ISSUE TITLE
회전변환 버그 수정

### ISSUE THREAD

**Issue by loonl** [kookmin-sw/capstone-2023-19#9]
f
Turn
두 기능에 문제 있는 것으로 추정

**Comment by loonl** [comment]
TurnAround 수정 완료
Euler -> Quaternion 으로 변환 후 회전행렬 곱하도록 코드 수정
f3e7b7ad7b0fae26f2b5a8a0f9e5c1add925177c

발견된 버그 : F-F, -FF 등 - + 가 제대로 작동하지 않음. (바로 위에 나오지 않고 옆으로 삐져나와서 그려짐)

**Comment by loonl** [comment]
https://github.com/kookmin-sw/capstone-2023-19/commit/3aadd0df9f5b724d830da9032c14bb0f6c84766c
1. 예상했던 짐벌락 현상 원인 확실시
2. 지난 2주간 Quaternion으로의 변환을 시도하였으나, 지식 부족과 정보 부족으로 구현에 계속 실패
3. 기존의 Euler 축 회전행렬 적용 순서인 Z->Y->X 에서 X->Y->Z로 수정하여 임시방편으로 짐벌락 현상 해결

당장은 해결했으나, 또다시 짐벌락 현상은 일어날 것이기 때문에 이에 맞게 코드를 수정할 생각. (좀 더 공부 필요)
미해결 : (짐벌락 현상에 의한) Hilbert Curve 3D

**Comment by jehyeon** [comment]
9071b58cadf5fb58650b33b940cc854bc42bd111
de2e3f9df2b74180b3cd2623fc85300996f1f06a
